pool:
      vmImage: 'VS2017-Win2016'
steps:
- script: |
    dotnet restore
    dotnet build --configuration Release
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration Release --output publish_output'
    projects: '*.csproj'
    publishWebProjects: false
    modifyOutputPath: false
    zipAfterPublish: false
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/infra'
    Contents: '**'
    TargetFolder: '$(System.DefaultWorkingDirectory)/publish_output'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/publish_output'
    ArtifactName: 'drop'
    publishLocation: 'Container'