name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
   AZURE_WEBAPP_NAME: 'frostmotorsport-ttt-app'
   AZURE_WEBAPP_PACKAGE_PATH: '.'
   ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    # - name: Publish  
    #   run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
    - uses: actions/upload-artifact@main
      with:
        name: webpack artifacts
        path: public/
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    #- name: Publish  

   #   run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' 

  Deploy-to-Azure:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy app to Azure
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: actions/checkout@v2
      - uses: actions/download-artifact@main
        with: 
          name: webpack artifacts
          path: public/
      - name: Deploy web app 
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

      - name: Azure logout
        run: |
          az logout
